import { useEffect, useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { useQuery } from '@tanstack/react-query'
import { AuthLoading } from '@/components/CustomerAuthLayout'
import { ArrowRight, Check, CircleHelp, Gauge, MapPin, Menu, ShieldCheck, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { TrailerImage } from '@/components/TrailerImage'
import { OcoLockup } from '@/components/OcoLogo'
import { BookingSearchForm } from '@/components/BookingSearchForm'
import { Location, TRAILER_COLUMNS, Trailer, formatMoney } from '@/lib/booking'
import { supabase } from '@/lib/supabase'

export const Route = createFileRoute('/')({
  head: () => ({ meta: [
    { title: 'OCO Trailer Rentals · Haul More. Go Further.' },
    { name: 'description', content: 'Dependable car hauler rentals in Anchorage and Omaha.' },
  ] }),
  component: HomeContent,
})

const EMPTY_LOCATIONS: Location[] = []

function HomeContent() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [isHydrated, setIsHydrated] = useState(false)
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- mount marker prevents SSR/client data divergence
    setIsHydrated(true)
  }, [])
  const locationsQuery = useQuery({ queryKey: ['public-locations'], enabled: isHydrated, queryFn: async () => { const { data, error } = await supabase.from('oco_locations').select('id,name,city,state,timezone').eq('is_active', true).order('name'); if (error) throw error; return (data ?? []) as Location[] } })
  const trailersQuery = useQuery({ queryKey: ['public-trailers'], enabled: isHydrated, queryFn: async () => { const { data, error } = await supabase.from('oco_available_trailers').select(TRAILER_COLUMNS).eq('is_active', true).order('name'); if (error) throw error; return (data ?? []) as unknown as Trailer[] } })
  const locations = locationsQuery.data ?? EMPTY_LOCATIONS
  // Rates come from the fleet, never from a number typed into the page. An empty
  // or still-loading fleet shows nothing rather than a stale figure.
  const dailyRates = (trailersQuery.data ?? []).map(trailer => Number(trailer.daily_rate)).filter(rate => Number.isFinite(rate) && rate > 0)
  const lowestDailyRate = dailyRates.length ? Math.min(...dailyRates) : null
  const locationName = (id: string) => locations.find(location => location.id === id)?.city ?? 'OCO location'
  if (!isHydrated) return <AuthLoading label="Loading OCO Rentals…" />
  return (
    <main className="min-h-dvh overflow-hidden bg-background">
      <nav className="absolute inset-x-0 top-0 z-20 border-b border-sidebar-foreground/10 bg-sidebar/95 text-sidebar-foreground backdrop-blur-md"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><a href="#top" aria-label="OCO Trailer Rentals — home"><OcoLockup /></a><div className="hidden items-center gap-8 text-sm text-sidebar-foreground/75 md:flex"><a href="#fleet" className="hover:text-sidebar-foreground">Fleet</a><a href="#how-it-works" className="hover:text-sidebar-foreground">How it works</a><a href="#locations" className="hover:text-sidebar-foreground">Locations</a><a href="/login"><Button variant="outline" className="border-sidebar-foreground/30 bg-transparent text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-foreground">Sign in</Button></a></div><button aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)} className="rounded-md p-2 hover:bg-sidebar-accent md:hidden">{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <div className="space-y-1 border-t border-sidebar-foreground/10 px-5 py-4 md:hidden"><a href="#fleet" className="block rounded-md px-3 py-2 hover:bg-sidebar-accent">Fleet</a><a href="#how-it-works" className="block rounded-md px-3 py-2 hover:bg-sidebar-accent">How it works</a><a href="#locations" className="block rounded-md px-3 py-2 hover:bg-sidebar-accent">Locations</a><a href="/login" className="block rounded-md px-3 py-2 hover:bg-sidebar-accent">Sign in</a></div>}</nav>
      <section id="top" className="relative isolate bg-sidebar pb-24 pt-36 text-sidebar-foreground lg:pb-32 lg:pt-48"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_82%_18%,oklch(0.55_0.075_226_/_0.32),transparent_32%),linear-gradient(110deg,oklch(0.165_0.021_231),oklch(0.275_0.028_229))]" /><div className="mx-auto grid max-w-7xl items-end gap-12 px-5 lg:grid-cols-[1fr_0.9fr] lg:px-8"><div className="max-w-2xl animate-fade-in"><p className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.25em] text-primary"><span className="h-px w-8 bg-primary" /> Reliable equipment. Straightforward rental.</p><h1 className="font-serif text-5xl leading-[0.98] tracking-tight text-sidebar-foreground sm:text-7xl">Haul more.<br /><em className="font-normal text-primary">Go further.</em></h1><p className="mt-7 max-w-lg text-base leading-7 text-sidebar-foreground/70 sm:text-lg">Professional car haulers for PCS moves, projects, and the miles in between. Book with confidence in Anchorage or Omaha.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#book"><Button className="h-12 gap-2 bg-primary px-6 text-primary-foreground shadow-lg transition-transform hover:scale-[1.02]">Find a trailer <ArrowRight className="h-4 w-4" /></Button></a><a href="#fleet"><Button variant="ghost" className="h-12 text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-foreground">Explore the fleet</Button></a></div><div className="mt-12 flex flex-wrap gap-x-7 gap-y-3 text-xs text-sidebar-foreground/60"><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-primary" /> Maintained & inspected</span><span className="flex items-center gap-2"><Gauge className="h-4 w-4 text-primary" /> Transparent rates</span></div></div><div className="relative hidden lg:block"><div className="absolute -inset-8 rounded-full bg-primary/10 blur-3xl" /><TrailerImage src={trailersQuery.data?.[0]?.image_url} alt="Car hauler trailer ready for rental" className="relative h-[440px] w-full rounded-[2rem] shadow-2xl ring-1 ring-sidebar-foreground/15" /><div className="absolute -bottom-5 -left-5 rounded-xl border border-sidebar-foreground/15 bg-sidebar/90 px-5 py-4 shadow-xl backdrop-blur"><p className="text-xs uppercase tracking-widest text-sidebar-foreground/55">Serving two cities</p><p className="mt-1 font-serif text-lg">Alaska to the Heartland</p></div></div></div></section>
      <section id="book" className="relative z-10 mx-auto -mt-10 max-w-6xl px-5 lg:-mt-16"><Card className="border-border/70 bg-card shadow-lg"><CardContent className="p-5 sm:p-8"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Start your rental</p><h2 className="mt-2 font-serif text-3xl">Where are you hauling?</h2></div>{lowestDailyRate !== null && <span className="rounded-full bg-secondary px-3 py-1 text-xs text-secondary-foreground">Rates from {formatMoney(lowestDailyRate)} / day</span>}</div><BookingSearchForm locations={locations} isLoading={locationsQuery.isLoading} loadError={locationsQuery.error} /></CardContent></Card></section>
      <section id="fleet" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="mb-10 flex items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">The fleet</p><h2 className="mt-3 font-serif text-4xl sm:text-5xl">Ready for the road.</h2></div><a href="#book" className="hidden items-center gap-2 text-sm font-semibold text-primary hover:underline sm:flex">Check availability <ArrowRight className="h-4 w-4" /></a></div>{trailersQuery.isLoading ? <div className="rounded-2xl border border-dashed border-border p-8 text-sm text-muted-foreground">Loading the current OCO fleet…</div> : trailersQuery.error ? <div role="alert" className="rounded-2xl border border-destructive/30 bg-destructive/10 p-8 text-sm text-destructive">We could not load the fleet right now: {trailersQuery.error.message}</div> : <div className="grid gap-6 md:grid-cols-2">{(trailersQuery.data ?? []).map(trailer => <article key={trailer.id} className="group overflow-hidden rounded-2xl border border-border bg-card shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-md"><div className="relative h-64 overflow-hidden"><TrailerImage src={trailer.image_url} alt={trailer.name} className="h-full w-full transition-transform duration-500 group-hover:scale-105" /><span className="absolute left-4 top-4 rounded-full bg-sidebar px-3 py-1 text-xs font-semibold text-sidebar-foreground">{locationName(trailer.location_id)}</span></div><div className="p-6"><div className="flex items-start justify-between gap-4"><div><h3 className="font-serif text-2xl">{trailer.name}</h3><p className="mt-2 text-sm text-muted-foreground">{trailer.description || 'OCO equipment details are being updated.'}</p></div><span className="text-right text-sm font-bold text-primary">${Number(trailer.daily_rate).toFixed(0)}<span className="block text-xs font-normal text-muted-foreground">per day</span></span></div><div className="mt-6 flex items-center justify-between border-t border-border pt-4 text-sm"><span className="flex items-center gap-2 text-muted-foreground"><Check className="h-4 w-4 text-primary" /> Inspected before every rental</span><a href={`/trailers/${trailer.slug}`} className="font-semibold text-foreground hover:text-primary">Details <ArrowRight className="ml-1 inline h-3 w-3" /></a></div></div></article>)}</div>}</section>
      <section id="how-it-works" className="bg-secondary/55"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="max-w-xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">How it works</p><h2 className="mt-3 font-serif text-4xl">Simple from start to finish.</h2></div><div className="mt-12 grid gap-8 md:grid-cols-3">{[['01', 'Choose your location', 'Tell us when and where you need a trailer. Same-location and one-way rentals are supported.'], ['02', 'Pick your trailer', 'Compare fit, equipment, and clear pricing before you commit.'], ['03', 'Haul with confidence', 'Complete a guided inspection, grab the keys, and get moving.']].map(([number, title, copy]) => <div key={number} className="border-t-2 border-primary pt-5"><span className="font-mono text-sm text-primary">{number}</span><h3 className="mt-8 font-serif text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p></div>)}</div></div></section>
      <section id="locations" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Find us</p><h2 className="mt-3 font-serif text-4xl sm:text-5xl">Two locations.<br />One dependable standard.</h2><p className="mt-6 max-w-md leading-7 text-muted-foreground">Our local teams keep every trailer ready, every rate clear, and every handoff straightforward.</p></div><div className="grid gap-4 sm:grid-cols-2">{locations.map(location => <div key={location.id} className="rounded-2xl border border-border bg-card p-6 shadow-sm"><MapPin className="h-6 w-6 text-primary" /><p className="mt-10 font-serif text-2xl">{location.name}</p><p className="mt-2 text-sm text-muted-foreground">{location.city}, {location.state} service center</p><a href="#book" className="mt-6 inline-block text-sm font-semibold text-primary hover:underline">Check availability <ArrowRight className="ml-1 inline h-3 w-3" /></a></div>)}</div></div></section>
      <footer className="bg-sidebar text-sidebar-foreground"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-12 lg:flex-row lg:items-end lg:justify-between lg:px-8"><div><OcoLockup className="h-9" /><p className="mt-4 text-sm text-sidebar-foreground/55">Haul More. Go Further.</p></div><div className="flex flex-wrap gap-5 text-sm text-sidebar-foreground/60"><a href="#how-it-works" className="hover:text-sidebar-foreground">FAQ</a><a href="#locations" className="hover:text-sidebar-foreground">Contact</a><a href="#top" className="hover:text-sidebar-foreground">Rental policy</a><span className="flex items-center gap-1"><CircleHelp className="h-4 w-4" /> Need help?</span></div></div></footer>
    </main>
  )
}

