/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BookRouteImport } from './routes/book'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppReservationsRouteImport } from './routes/app/reservations'
import { Route as AppReservationsReservationIdRouteImport } from './routes/app/reservations.$reservationId'
import { Route as TrailersSlugRouteImport } from './routes/trailers.$slug'
import { Route as AppBookRouteImport } from './routes/app/book'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppAdminRouteImport } from './routes/app/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailersSlugRoute = TrailersSlugRouteImport.update({
  id: '/trailers/$slug',
  path: '/trailers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsReservationIdRoute =
  AppReservationsReservationIdRouteImport.update({
    id: '/$reservationId',
    path: '/$reservationId',
    getParentRoute: () => AppReservationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/book': typeof BookRoute
  '/terms': typeof TermsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reserve': typeof ReserveRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/trailers/$slug': typeof TrailersSlugRoute
  '/app/admin': typeof AppAdminRoute
  '/app/book': typeof AppBookRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/reservations': typeof AppReservationsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/reservations/$reservationId': typeof AppReservationsReservationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/terms': typeof TermsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reserve': typeof ReserveRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/trailers/$slug': typeof TrailersSlugRoute
  '/app/admin': typeof AppAdminRoute
  '/app/book': typeof AppBookRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/reservations': typeof AppReservationsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/reservations/$reservationId': typeof AppReservationsReservationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/book': typeof BookRoute
  '/terms': typeof TermsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reserve': typeof ReserveRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/trailers/$slug': typeof TrailersSlugRoute
  '/app/admin': typeof AppAdminRoute
  '/app/book': typeof AppBookRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/reservations': typeof AppReservationsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/reservations/$reservationId': typeof AppReservationsReservationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/book'
    | '/terms'
    | '/forgot-password'
    | '/login'
    | '/reserve'
    | '/reset-password'
    | '/signup'
    | '/trailers/$slug'
    | '/app/admin'
    | '/app/book'
    | '/app/documents'
    | '/app/reservations'
    | '/app/'
    | '/app/reservations/$reservationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/terms'
    | '/forgot-password'
    | '/login'
    | '/reserve'
    | '/reset-password'
    | '/signup'
    | '/trailers/$slug'
    | '/app/admin'
    | '/app/book'
    | '/app/documents'
    | '/app/reservations'
    | '/app'
    | '/app/reservations/$reservationId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/book'
    | '/terms'
    | '/forgot-password'
    | '/login'
    | '/reserve'
    | '/reset-password'
    | '/signup'
    | '/trailers/$slug'
    | '/app/admin'
    | '/app/book'
    | '/app/documents'
    | '/app/reservations'
    | '/app/'
    | '/app/reservations/$reservationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BookRoute: typeof BookRoute
  TermsRoute: typeof TermsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ReserveRoute: typeof ReserveRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TrailersSlugRoute: typeof TrailersSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trailers/$slug': {
      id: '/trailers/$slug'
      path: '/trailers/$slug'
      fullPath: '/trailers/$slug'
      preLoaderRoute: typeof TrailersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/book': {
      id: '/app/book'
      path: '/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reservations': {
      id: '/app/reservations'
      path: '/reservations'
      fullPath: '/app/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reservations/$reservationId': {
      id: '/app/reservations/$reservationId'
      path: '/$reservationId'
      fullPath: '/app/reservations/$reservationId'
      preLoaderRoute: typeof AppReservationsReservationIdRouteImport
      parentRoute: typeof AppReservationsRoute
    }
  }
}

interface AppReservationsRouteChildren {
  AppReservationsReservationIdRoute: typeof AppReservationsReservationIdRoute
}

const AppReservationsRouteChildren: AppReservationsRouteChildren = {
  AppReservationsReservationIdRoute: AppReservationsReservationIdRoute,
}

const AppReservationsRouteWithChildren = AppReservationsRoute._addFileChildren(
  AppReservationsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBookRoute: typeof AppBookRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppReservationsRoute: typeof AppReservationsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBookRoute: AppBookRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppReservationsRoute: AppReservationsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BookRoute: BookRoute,
  TermsRoute: TermsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ReserveRoute: ReserveRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TrailersSlugRoute: TrailersSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
