/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppReservationsRouteImport } from './routes/app/reservations'
import { Route as AppReservationsReservationIdRouteImport } from './routes/app/reservations.$reservationId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsReservationIdRoute =
  AppReservationsReservationIdRouteImport.update({
    id: '/$reservationId',
    path: '/$reservationId',
    getParentRoute: () => AppReservationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/reserve': typeof ReserveRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/reservations': typeof AppReservationsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/reservations/$reservationId': typeof AppReservationsReservationIdRoute
}
export interface FileRoutesByTo {
  '/reserve': typeof ReserveRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/reservations': typeof AppReservationsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/reservations/$reservationId': typeof AppReservationsReservationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/reserve': typeof ReserveRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/reservations': typeof AppReservationsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/reservations/$reservationId': typeof AppReservationsReservationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/reserve'
    | '/reset-password'
    | '/signup'
    | '/app/reservations'
    | '/app/'
    | '/app/reservations/$reservationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/reserve'
    | '/reset-password'
    | '/signup'
    | '/app/reservations'
    | '/app'
    | '/app/reservations/$reservationId'
  id:
    | '__root__'
    | '/reserve'
    | '/reset-password'
    | '/signup'
    | '/app/reservations'
    | '/app/'
    | '/app/reservations/$reservationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ReserveRoute: typeof ReserveRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reservations': {
      id: '/app/reservations'
      path: '/reservations'
      fullPath: '/app/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reservations/$reservationId': {
      id: '/app/reservations/$reservationId'
      path: '/$reservationId'
      fullPath: '/app/reservations/$reservationId'
      preLoaderRoute: typeof AppReservationsReservationIdRouteImport
      parentRoute: typeof AppReservationsRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ReserveRoute: ReserveRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
